JDK provider incorrectly configures default ciphers for TLSv1.3
Motivation:

We use the old approach of configuring secure protocols in netty via
`SSLEngine#setEnabledProtocols(...)`. In this case, `SslContextBuilder`
does not know if users configure TLSv1.3 or not and therefore, sets
incorrect set of default ciphers which does not support TLSv1.3.
As the result, users see:
javax.net.ssl.SSLHandshakeException: No appropriate protocol
(protocol is disabled or cipher suites are inappropriate).

Modifications:

- Use `SslContextBuilder#protocols(...)` instead of
`SSLEngine#setEnabledProtocols(...)` to set secure protocols;
- Delete `WrappingSslContext` that is not required anymore;

Result:

`SslContextBuilder` correctly sets default ciphers when TLSv1.3
is present.