NettyCompression gzip streaming decompression over multiple buffers fix (#2380)
Motivation:
NettyCompression's gzip streaming decompression fails to decompress
payloads when split over multiple buffers and may result in:

```
DecompressionException: Input is not in the GZIP format
```

Modifications:
- NettyCompressionStreamingSerializer skips bytes unconditionally after
  they are feed to the Netty decoders. However in some scenarios not all
  bytes maybe consumed, and if we skip the bytes the aggregation maintained
  by Netty's ByteToMessageDecoder will be discarded. Instead of skipping
  unconditionally we should only advance the reader index if the ByteBuf
  and Buffer don't already match.