Remove bad use of '>' in javadoc
Motivation:

`javadoc` task failed with `PortRegistry.java:21: error: bad use of '>'`.

Modification:

- Use `to` instead of `->` in javadoc of `PortRegistry.java`;

Result:

`javadoc` task doesn't fail anymore.